### ISSUE TITLE
ANSI is fubared

### ISSUE THREAD

**Issue by mrsenile** [TinyMUSH/TinyMUSH#1] opened 2015-07-05 01:12 UTC
Ansi handing is fubared.  The results do not display properly.  Any manipulation by a majority of functions will either cut it off or in the case of functions (like edit(), scramble(), or the like) have a high risk of crashing the mush.

Examples:  
think scramble(ansi(hr,red)) -- boom
edit(ansi(hr,red),e,x) -- cut off and the occasional boom
foreach() or other character based functions do not handle ansi at all.
256 coloring is not fully vested in compatibility with RhostMUSH, PennMUSH, and TinyMUX

**Comment by EddyBeaupre** [comment] 2015-07-05 11:35
think scramble(ansi(hr,red)) : Work, can't reproduce the bug in the the git version.
think edit(ansi(hr,red),e,x) : Work, can't reproduce the bug in the the git version.
foreach() or other character based functions do not handle ansi at all : By design, but already in the todo list for 3.3 at a later stage.
256 coloring is not fully vested in compatibility with RhostMUSH, PennMUSH, and TinyMUX: By design, but already in the todo list for 3.3 at a later stage.

**Comment by mrsenile** [comment] 2015-09-24 18:33
Ok, verified, I had Release 8 and not 9.

With 9, ansi is still fubared, just not as bad.

Issues:
1. it looks like background color is always black, regardless of specifying it or not.
2. stripansi() doesn't work.
3. intense ansi bleed with most functions and commands.
4. @colormap hangs the mush into an infinite loop (@colormap r=r then r=y did it)
5. @colormap doesn't map properly.
6. edit() doesn't work, at all or at least seems to make characters dissapear.

**Comment by EddyBeaupre** [comment] 2015-09-24 19:05
All known issues... still alpha...


Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : mrsenile <notifications@github.com> 
Date : 09/24/2015  2:33 PM  (GMT-05:00) 
À : TinyMUSH/TinyMUSH <TinyMUSH@noreply.github.com> 
Cc : Eddy Beaupré <eddy@beaupre.biz> 
Objet : Re: [TinyMUSH] ANSI is fubared (#1) 

Ok, verified, I had Release 8 and not 9.

With 9, ansi is still fubared, just not as bad.

Issues:

1. it looks like background color is always black, regardless of specifying it or not.

2. stripansi() doesn't work.

3. intense ansi bleed with most functions and commands.

4. @colormap hangs the mush into an infinite loop (@colormap r=r then r=y did it)

5. @colormap doesn't map properly.

6. edit() doesn't work, at all or at least seems to make characters dissapear.

**Comment by EddyBeaupre** [comment] 2020-12-07 23:32
Most of theses bugs are caused by the old memory/string manager. There's alot of changes going on right now in that area. Closing this bug for now but it's all noted for futur testings.

**Closed by EddyBeaupre** 2020-12-07 23:32 UTC
